version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - microdepressivos_networking
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules:/etc/prometheus/alert.rules
    ports:
      - 9090:9090
    networks:
      - microdepressivos_networking
  app:
    build:
      context: .
    restart: on-failure
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - 5000:5000
    networks:
      - microdepressivos_networking
    depends_on:
      - rabbitmq
      - prometheus

networks:
  microdepressivos_networking: {}
