name: Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.7

      - uses: Gr1N/setup-poetry@v4
        with:
          poetry-version: 1.0.10

      - name: Install dependencies and packages
        run: poetry install

      - name: Run the test Script
        run: poetry run python -m unittest
